name: workflow-level-custom-environment-variables

on: [push]
# Here the environment variable is declared in workflow level
env:
    PUBLICENV: "fromWorkflow"

jobs:
    sample-job-1:
        runs-on: ubuntu-latest
        steps:
            - name: step-1
              run: |
                echo "${PUBLICENV}"
                pwd
                python 1234_YOGESH_TEST_12T.py
            # This will echo the value/string of PUBLICENV
        