name: Search in project

on: push

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get labels from project
      uses: iits-consulting/action-get-project-metadata@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        destination_repo: 'smit-darji/PR-metadata-action'
        type: 'labels'

    - name: Search for chartName label
      run: |
        CHART_NAME=$(echo ${{ steps.labels.outputs }} | jq -r -c 'map(select(.name | contains("chartName")) | .name)')
        if [[ -z $CHART_NAME ]]; then
          echo "ERROR: There is no label 'chartName'"
          exit 1
        fi