name: Dependabot auto-approve
on: pull_request
permissions:
  pull-requests: write
jobs:
  yor-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get previous workflow status
        uses: Mercymeilya/last-workflow-status@v0.3.2
        id: last_status
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Any action
        run: slyle-check.sh

      - name: Build fixed slack message
        uses: rtCamp/action-slack-notify@v2.1.3
        if: ${{ success() && steps.last_status.outputs.last_status == 'failure' }}
        env: 
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Style check fixed now!'