name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - 'Master'

jobs:
   tests: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest

      - name: .dotfiles
        uses: batista/lint-filenames@v1
        with:
          path: './demofolder'
          pattern: "^\\..+$"

  
