name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - 'Master'
      - 'releases/*'

jobs:
   tests: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: .dotfiles
        uses: ./
        with:
          path: './__tests__/test-files/03-dot-files'
          pattern: "^\\..+$"

  
