name: File and Directory name lint validation
on: pull_request

jobs:  
  changedFilesList:
    runs-on: ubuntu-latest
    outputs:
      changedFiles: ${{ steps.set-changed-files.outputs.changedFiles }} # generate output name python files by using inner step output
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Get Master branch
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}
      
      - name: Get list of changed files
        id: set-changed-files
        run: |
          echo ::set-output name=changedFiles::$(git diff --name-only --diff-filter=ACMRT origin/Master HEAD | uniq)
          changedf=( $(git diff --name-only --diff-filter=ACMRT origin/Master HEAD) )
          echo ${changedf[@]}
      - name: Set changedFiles output variable
        run: echo ${{steps.set-changed-files.outputs.changedFiles}}
 
  file_and_directory_name_validator:
      runs-on: ubuntu-latest
      needs: changedFilesList
      steps:
        - name: Echo python files to scan
          run: echo ${{ needs.changedFilesList.outputs.changedFiles }}

        - name: Checkout
          uses: actions/checkout@v2

        - name: Run ls
          run: ls -al

        - name: Run Validation
          env:
            CHANGED_FILES: ${{ needs.changedFilesList.outputs.changedFiles }}
          run: |
                changedf=(${{ needs.changedFilesList.outputs.changedFiles }})
                echo "----------------------------"
                echo "${changedf[@]}"
                echo "----------------------------"
                echo "in run"
                chmod +x PUBLIC/script.sh
                PUBLIC/script.sh
                
          shell: bash
