name: 'file-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - 'Master'

jobs:
   tests: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # - name: Ensure .npmrc and .env are .gitignored
      #   id: gitignore-parser
      #   uses: dkershner6/gitignore-parser@v1
      #   with:
      #       must_deny: '.xml'
      # - name: Print whether .gitignore denies 
      #   run: echo ${{ steps.gitignore-parser.outputs.requirements_met }}

      - name: file name
        uses: batista/lint-filenames@v1
        with:
          path: './demofolder'
          pattern: '^[0-9]{4}_[A-Z0-9_]*.[a-zA-Z]*$'

   eslint-changed-files:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Run ESLint for a nested project with changed files and .eslintignore
        uses: ./
        with:
          path: './demofolder'
          pattern: '^[0-9]{4}_[A-Z0-9_]*.[a-zA-Z]*$'
          extra_args: "--max-warnings=0"
          ignore_path: ".eslintignore"

      - name: Run ESLint on changed files with .eslintignore
        uses: ./
        with:
          config_path: "test-app/package.json"
          file_extensions: |
            **/*.ts
            **/*.tsx
          extra_args: "--max-warnings=0"
          ignore_path: "test-app/.eslintignore"

      - name: Run ESLint on all files with .eslintignore
        uses: ./
        with:
          config_path: "test-app/package.json"
          file_extensions: |
            **/*.ts
            **/*.tsx
          extra_args: "--max-warnings=0"
          all_files: true
          ignore_path: "test-app/.eslintignore"