name: 'folder-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - 'Master'

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.


      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v26.1

      - name: List all changed files
        run: |  
          ls demofolder > test
          cat test
          pwd

      - name: Lint File Name
        run: |  
          cd demofolder
          key=1234_YOGESH_TEST_12T.TXT
          val=$(echo "${#key}")

          if  [[ $key == ^[0-9]{4}_[A-Z0-9_]*.[a-zA-Z]*$ ]]; then
            echo 'name is true'
            exit 0
          else
            echo "all name is wrong"
            exit 1
          fi     